 services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports: 
      - 5050:5050
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6378:6379"
    command: redis-server --save 60 1 --loglevel warning
 volumes:
  postgres_data: