spring.application.name=Birdup
spring.datasource.url=jdbc:postgresql://localhost:5332/birdup
spring.datasource.username=birdup
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5050/realms/web

ebird.api.key=${EBIRD_API_TOKEN}
