events {}

http {
    limit_req_zone $binary_remote_addr zone=limit:10m rate=2r/s;

    server {
        listen 80;
        server_name localhost;

        location /api {
            limit_req zone=limit burst=5;
            # NOTE replace "host.docker.internal" with api container name
            proxy_pass http://host.docker.internal:8080;
        }
    }
}

