package org.birdup.api.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "users")
public class User {

    @Id
    private String userId; // uuid generated by Keycloak
    private String email;
    private LocalDateTime createdAt;

    public User() {}

    public User(String userId, String email) {
        this.userId = userId;
        this.email = email;
        this.createdAt = LocalDateTime.now();
    }
}